version: "3.9"

services:
  ollama:
    environment:
      OLLAMA_GPU: "true"
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - gpu

  comfyui:
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - gpu
    environment:
      - CLI_ARGS=--listen 0.0.0.0 --port 8188 --cuda-device 0
